### ISSUE TITLE
Iyer et al. 2004

### ISSUE THREAD

**Issue by MichaelClerx** [PMR2/models.physiomeproject.org#41]
Current exposure: https://models.physiomeproject.org/exposure/e0922113f8ca0258441cc9f3d53dcc08
Updated workspace: https://models.physiomeproject.org/workspace/6fb

In the available file, `tau _yCa` is given as `1 / ( 0.00336... / (0.5 + exp(-V / 5.54...)) + 0.00790... * exp(-V / 49.5...) )`. This has been changed to `1 / (0.00653 / (0.5 + exp(-V / 7.1)) + 0.00512 * exp(-V / 39.8))` in accordance with the published equations.

An updated workspace is available (see above).

Requested action: Build exposure from workspace above (I don't know how to do this and get the same result as the original exposure), then expire previous exposure.

See: https://github.com/CardiacModelling/ical-model-review/blob/master/Models/README.md

**Comment by aram148** [comment]
Requested action has been completed. Please take a look and let us know what you think.

**Comment by MichaelClerx** [comment]
Thank you!
