### ISSUE TITLE
[Workspace]: Computational analysis of the human sinus node action potential: model development and effects of mutations

### ISSUE THREAD

**Issue by ML0401** [PMR2/models.physiomeproject.org#61]
### URI of the workspace

https://models.cellml.org/workspace/486

### The issue encountered with the workspace

Hello, 

I was working on converting the cellML code of the Severi et al. model into openCARP readable EasyML based on the tutorials and examples on the openCARP homepage. 

After declaring the transmembrane voltage and sorting out the issues with the gating variables I received a key error stating that the key Kc is unknown. After looking into the supplementary material more closely I suggest that in the declaration of the funny current If Kc is a typo and needs to be renamed into Ko. Furthermore, Ko needs to be initialised in the constants section. Is this the intended way to go or did I miss something?

**Comment by nickerso** [comment]
Hi, thanks for the feedback. Just to clarify, is it the If definition in the CellML model or the supplementary information that is incorrect? I'm not seeing a `Kc` variable in the CellML model and the If current is using `Ko`. As this CellML model was contributed by the author of the Fabbri, Fantini, Wilders & Severi (2017) model, I suspect that you are correct in suggesting `Ko` should be used in the If current declaration.

**Comment by ML0401** [comment]
They are inconsistent. Based on the supplementary material the cellML file is wrong. following this link [https://models.cellml.org/e/139/severi_fantini_charawi_difrancesco_2012.cellml/source_text](url) there are a few `Kc` variables used without a declaration of `Kc` which is why I received the key error. 

There are two problems: 
1) In the supplementary material we have `Ko` in the definition of `If`. Following this `Kc` has to be renamed into `Ko`.
2) Neither `Kc` nor `Ko` are defined in the cellML file. Based on the supplementary material I suggest that the fix value of 5.4 mmol/L would be correct.
It is also possible to just define `Kc` in the cellML file or the translated EasyML but in this case the inconsistence with the supplementary material would remain present.

**Comment by nickerso** [comment]
Great, thanks for clarifying @ML0401. For completeness, this is actually the model in https://models.cellml.org/w/sseveri/severi_fantini_charawi_difrancesco_2012 (not the derived Fabbri et al model that is in https://models.cellml.org/workspace/486). Again, this model was contributed by the original author of the model so hopefully its correct.

Looking at the CellML, the variable `Kc` used in a few of the current components (I_f, I_NaK, I_Na, I_CaL) and for each of these is connected to the `Ko` variable in the `Ionic_values` component. So while I'm not sure why the author decided to call the variable `Kc` in these cases, it is valid and complete CellML.

Not sure if this explanation helps in your case as I've not familiar with OpenCARP and the EasyML format.

**Comment by ML0401** [comment]
Ok thanks, yes you are right `Ko` is already defined so I think it is best to rename `Kc` into `Ko` in the EasyML file. I just wanted to make sure that my suggestions about the connection of `Kc` and `Ko` are correct. Maybe there is a problem in the translation of the code from cellML into EasyML leading to a loss of that connection.
